export const importScreenKey = [
    'componentContainerConfig.json',
    'componentContainerRelsConfig.json',
    'componentCustomInfo.json',
    'componentsConfig.json',
    'containersConfig.json',
    'filterConfig.json',
    'info.json',
    'panelConfig.json',
    'reservePlanCollectionConfig.json',
    'reservePlanConfig.json',
    'screenConfig.json',
    'sourceConfig.json',
    'scene.json',
    'blueprint.json',
    'constantsConfig.json',
]